version: "3.7"
services:
    db:
        image: mysql:8.0.19
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=example
            - MYSQL_ROOT_PASSWORD=password
        networks: 
            - backend
  
    app:
        build: app
        restart: always
        ports:
            - 5000:5000
        networks: 
            - backend
            - frontend
        # for debugging, apply code changes without having to rebuild the image
        volumes:
            - ./app/src:/code

volumes:
    db-data:
networks: 
    backend:
    frontend: